server:
  port: 8587
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: rms
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
    web-application-type: REACTIVE
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
  kafka:
    bootstrap-servers: localhost:9092
    # Consumer configurations (optional)
    consumer:
      group-id: my-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bootstrap-servers: localhost:9092
    # Producer configurations (optional)
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: localhost:9092

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8181/realms/test-realm
      client:
        provider:
          service-client:
            issuer-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}
        registration:
          service-client:
            client-name: service-client
            client-id: service-client
            client-secret: service-client-secret
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_basic
            scope:
              - openid
jima:
  feature:
    database-type: mongo
    database-enabled: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.validation: TRACE
    org.springframework.http.converter: TRACE
    org.springframework.web.servlet.mvc.method.annotation: TRACE
    org.springframework.http.codec.json: TRACE
    org.springframework.http.codec.json.Jackson2JsonDecoder: TRACE
    org.springframework.web.reactive.function.server.support.ServerRequestReader: TRACE
    org.springframework.web.reactive.result.method.annotation.RequestBodyMethodArgumentResolver: TRACE
